// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugpgyzmdzrhxxzugxyfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVncGd5em1kenJoeHh6dWd4eWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODYyOTUsImV4cCI6MjA3MDY2MjI5NX0.gDKcTkJHvMnp60zlykE564ZmqKnlwnMMlJGYLVqQVXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});